### PR TITLE
Provide ActiveQuery#none for situations where you want zero results, but...

### PR DESCRIPTION
**Pull request by DanOlson**
... still need the ActiveQuery interface

### CODE REVIEW

**Comment by olvap** [comment]
@DanOlson why do you need a method like a none?

**Comment by DanOlson** [comment]
@olvap I need it for polymorphism. I have a situation where in the case I have access to a certain value, I need to build up an `ActiveQuery` for records scoped to that value. If I don't have it, I still need the interface provided by `ActiveQuery`, but I don't want to actually run a query that will return results. A naive alternative would be to use an `Array` for the `else` clause, but `Array` doesn't respond to `where` or `limit` or any of the other methods I will be calling later.

For example, I have an intermediate service object that provides a base `ActiveQuery`, which will be consumed by other service objects and modified in different ways:

```ruby
module Salesforce
  class OpportunitiesDashboard
    # ...
    def opportunities
      if my_value
        Opportunity.includes(:owner, :account).where(my_field: my_value)
      else
        Opportunity.none
      end
    end

    #...
  end
end
```

I'd rather not actually make a request with `none`, but I'd like some feedback on that idea. One thing I could do is explicitly assign `@records` in the `ActiveQuery` instance:

```ruby
module ActiveForce
  class ActiveQuery < Query
    def none
      @records = []
      where(id: '1'*18).where(id: '0'*18)
    end
  end
end
```

This would mean I wouldn't _need_ the calls to `where`, but omitting them would make it pretty confusing for anyone inspecting the SOQL that is generated. In any case, I'm not sure I like that implementation... It seems a little too magical, but I do think it's sensible to not run a query.

**Comment by DanOlson** [comment]
@olvap Any thoughts on this?

**Comment by eloyesp** [comment]
I think it is a valid point, but the second implementation you provide seems more reasonable.

```ruby
module ActiveForce
  class ActiveQuery < Query
    def none
      @records = []
      where(id: '1'*18).where(id: '0'*18)
    end
  end
end
```

Another option, to prevent adding more methods, is to use something as:

```ruby
# sample usage
query.where(:none).includes(:owner, :account).where(my_field: my_value)

# implementation
module ActiveForce
  class ActiveQuery < Query
    def build_condition(args, other=[])
      case args
      when :none
        @records = [] # the query will not be evaluated
        'none'        # the query will fail if evaluated and `to_s` will be clear about intention
      # ...
      end
    end
  end
end
```

**Comment by DanOlson** [comment]
Thanks for the feedback @eloyesp ! I've implemented the second implementation, as it feels more AR-like to support `none` directly.

**Comment by eloyesp** [comment]
Thanks

**Pull request merged**
